export interface Member {
  name: string
  class: string
  isReady: boolean
}

export const memberData: Member[] = [
  { name: "5ly", class: "Tempest", isReady: false },
  { name: "AceB", class: "Tempest", isReady: false },
  { name: "Alucard1391", class: "Necromancer", isReady: false },
  { name: "Anomundi", class: "Wizard", isReady: false },
  { name: "Aphirym", class: "Crusader", isReady: false },
  { name: "arrogante", class: "Demon Hunter", isReady: false },
  { name: "Årtanis", class: "Barbarian", isReady: false },
  { name: "Blue8188120", class: "Demon Hunter", isReady: false },
  { name: "Bo0Tz", class: "Demon Hunter", isReady: false },
  { name: "bocharik", class: "Tempest", isReady: false },
  { name: "Brittnayy", class: "Demon Hunter", isReady: false },
  { name: "CarnageFest", class: "Necromancer", isReady: false },
  { name: "Catalin", class: "Demon Hunter", isReady: false },
  { name: "Chainus", class: "Crusader", isReady: false },
  { name: "CHRISTINEWLA", class: "Necromancer", isReady: false },
  { name: "Corol", class: "Blood Knight", isReady: false },
  { name: "DaisytheDane", class: "Necromancer", isReady: false },
  { name: "DannyDeadpool", class: "Necromancer", isReady: false },
  { name: "DeadlyWolf87", class: "Necromancer", isReady: false },
  { name: "Diabolically", class: "Monk", isReady: false },
  { name: "Dimitresku", class: "Barbarian", isReady: false },
  { name: "ÐïrtŷÐïnkž", class: "Wizard", isReady: false },
  { name: "Dredna", class: "Blood Knight", isReady: false },
  { name: "Driftie", class: "Barbarian", isReady: false },
  { name: "Duylan", class: "Demon Hunter", isReady: false },
  { name: "FireBlades", class: "Crusader", isReady: false },
  { name: "Fudu", class: "Barbarian", isReady: false },
  { name: "Ghettomagikz", class: "Monk", isReady: false },
  { name: "GrannySmith", class: "Tempest", isReady: false },
  { name: "GuardianBlade", class: "Crusader", isReady: false },
  { name: "HellPrinceBytor", class: "Blood Knight", isReady: false },
  { name: "HowlSimp", class: "Demon Hunter", isReady: false },
  { name: "HunterDaylan", class: "Demon Hunter", isReady: false },
  { name: "Impio", class: "Blood Knight", isReady: false },
  { name: "Invasion", class: "Crusader", isReady: false },
  { name: "iSymphony", class: "Monk", isReady: false },
  { name: "J0K3R8623", class: "Necromancer", isReady: false },
  { name: "Jaracuda1976", class: "Demon Hunter", isReady: false },
  { name: "JoeY0510", class: "Tempest", isReady: false },
  { name: "JugJr", class: "Blood Knight", isReady: false },
  { name: "Justin088", class: "Blood Knight", isReady: false },
  { name: "Kaine84", class: "Tempest", isReady: false },
  { name: "Kasreyn", class: "Wizard", isReady: false },
  { name: "Kelan", class: "Barbarian", isReady: false },
  { name: "KILLOS", class: "Crusader", isReady: false },
  { name: "KobyM", class: "Tempest", isReady: false },
  { name: "Kwisatz", class: "Crusader", isReady: false },
  { name: "LadonnaNuitari", class: "Wizard", isReady: false },
  { name: "LadyxKraken", class: "Tempest", isReady: false },
  { name: "LordViro", class: "Monk", isReady: false },
  { name: "Lostacount", class: "Blood Knight", isReady: false },
  { name: "Mac", class: "Barbarian", isReady: false },
  { name: "Mastercain", class: "Barbarian", isReady: false },
  { name: "MevesYsufreS", class: "Crusader", isReady: false },
  { name: "Milandra", class: "Demon Hunter", isReady: false },
  { name: "MissBearr", class: "Demon Hunter", isReady: false },
  { name: "MissRenegade", class: "Demon Hunter", isReady: false },
  { name: "Motoralis", class: "Tempest", isReady: false },
  { name: "Musclemommyy", class: "Barbarian", isReady: false },
  { name: "Musherz", class: "Blood Knight", isReady: false },
  { name: "Necromantik", class: "Barbarian", isReady: false },
  { name: "Nightro", class: "Crusader", isReady: false },
  { name: "NoFlexiiiN", class: "Necromancer", isReady: false },
  { name: "ObliviousDingo", class: "Tempest", isReady: false },
  { name: "Oliverdo", class: "Crusader", isReady: false },
  { name: "P A T R O C O L O", class: "Tempest", isReady: false },
  { name: "Quîntus", class: "Crusader", isReady: false },
  { name: "RąvenSwørd", class: "Tempest", isReady: false },
  { name: "RexF", class: "Demon Hunter", isReady: false },
  { name: "Rizonance", class: "Necromancer", isReady: false },
  { name: "Rudest", class: "Tempest", isReady: false },
  { name: "Rynson1", class: "Monk", isReady: false },
  { name: "Sargon9", class: "Necromancer", isReady: false },
  { name: "Schtav", class: "Monk", isReady: false },
  { name: "SHADOb4u", class: "Necromancer", isReady: false },
  { name: "Sirloinn", class: "Demon Hunter", isReady: false },
  { name: "Stagnation", class: "Necromancer", isReady: false },
  { name: "StrawberryKnight", class: "Tempest", isReady: false },
  { name: "Stylar", class: "Wizard", isReady: false },
  { name: "Svarog", class: "Barbarian", isReady: false },
  { name: "SWOLeST", class: "Barbarian", isReady: false },
  { name: "Thânos", class: "Demon Hunter", isReady: false },
  { name: "Theonlyreason1", class: "Crusader", isReady: false },
  { name: "ThomasShelbyy", class: "Necromancer", isReady: false },
  { name: "TokyoChe", class: "Tempest", isReady: false },
  { name: "Tracis", class: "Necromancer", isReady: false },
  { name: "UUUuuTtZzz", class: "Tempest", isReady: false },
  { name: "Valgren", class: "Tempest", isReady: false },
  { name: "Varlie", class: "Tempest", isReady: false },
  { name: "Vuluxy", class: "Necromancer", isReady: false },
  { name: "YakshaKing", class: "Monk", isReady: false },
  { name: "YettiRampage", class: "Barbarian", isReady: false },
  { name: "Yugmudgib", class: "Barbarian", isReady: false },
  { name: "Zatra", class: "Monk", isReady: false },
  { name: "Zuvya", class: "Blood Knight", isReady: false },
  { name: "死死死 (DieDieDie)", class: "Necromancer", isReady: false },
]

